# Generated by Django 5.2.8 on 2025-11-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tasks'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='creater',
            managers=[
            ],
        ),
    ]
