# Generated by Django 5.2.8 on 2025-11-26 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_creater_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_key', models.CharField(max_length=256)),
                ('expire_time', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
