# Generated by Django 5.2.8 on 2025-11-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_requestedotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedotp',
            old_name='hashed_key',
            new_name='hashed_text',
        ),
    ]
