# Generated by Django 5.2.8 on 2025-11-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_hashed_key_requestedotp_hashed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
    ]
