# Generated by Django 5.2.8 on 2025-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
